#https://prospector.landscape.io/en/latest/profiles.html#enabling-and-disabling-tools

output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120

bandit:
  run: true

pylint:
  disable:
    - broad-except
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

pep8:
  full: true
  disable:
    - E126

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D107
    - D205
    - D400
    - D401
