name: Automerge PR

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/automerge-prs.yml@baac94b3959e9289608ba8d2a5675965462b1461 # v1.0.7
    secrets: inherit
