name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@25c75ee87712da38c41a86b9d197ce38effdff0c # v1.0.8
