name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-sbom:
    uses: tkhom3/gha-workflows/.github/workflows/generate-sbom.yml@main
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@main
    secrets: inherit
