name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@25c75ee87712da38c41a86b9d197ce38effdff0c # v1.0.8
    secrets: inherit
