name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@68f269256fbed22648f23ce579ddf356b95ef0f6 # v1.0.21
