name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
      uses: aquasecurity/trivy-action@0.31.0
      with:
        scan-type: 'fs'
        format: 'github'
        output: 'dependency-results.sbom.json'
        image-ref: '.'
        github-pat: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      - name: Login to DockerHub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.release.outputs.version }}
            ${{ github.repository }}:${{ steps.release.outputs.major }}
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:${{ github.sha }}
