name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@77da5499f0fe1a627dbe7932bdb21773f9eb3b46 # v1.0.11
    secrets: inherit
