name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@baac94b3959e9289608ba8d2a5675965462b1461 # v1.0.7
    secrets: inherit
